Improve "type cannot be {shared,realized}" diagnostics
Consider the following program:

    datatype a = A
    signature T =
       sig
          type a = a
          type b
          type c
          type d
          type t = a * b * c * d -> unit
       end
    signature S =
       sig
          type a
          type c
          structure T1:
             sig
                structure T2 :
                   sig
                      include T where type b = a
                                where type d = c
                   end
             end where type T2.t = unit
          structure T3:
             sig
                structure T4 :
                   sig
                      include T where type b = a
                                where type d = c
                   end
             end
          structure T5:
             sig
                structure T6 :
                   sig
                      include T where type b = a
                                where type d = c
                   end
             end
          sharing type T3.T4.t = T5.T6.t
       end

Previously, MLton generated the following error messages:

    Error: z.sml 21.25-21.28.
      Type cannot be realized (defined): T2.t.
        type spec: type T2.t = a * _sig.a * _sig.T1.T2.c * _sig.c -> unit
        spec at: z.sml 8.12-8.12
    Error: z.sml 38.20-38.26.
      Type cannot be shared (defined): T3.T4.t.
        type spec: type T3.T4.t = a * _sig.a * _sig.T3.T4.c * _sig.c -> unit
        spec at: z.sml 8.12-8.12
    Error: z.sml 38.30-38.36.
      Type cannot be shared (defined): T5.T6.t.
        type spec: type T5.T6.t = a * _sig.a * _sig.T5.T6.c * _sig.c -> unit
        spec at: z.sml 8.12-8.12

Although the use of "_sig" could be explained as "the top-level
signature being elaborated", it can still be confusing when shadowed
type constructors are not displayed with "?." prefixes.

Now, MLton generates the following error messages:

    Error: z.sml 21.25-21.28.
      Type cannot be realized (defined): T2.t.
        type spec: type T2.t = ?.a * a * _sig.T2.c * c -> unit
        spec at: z.sml 8.12-8.12
    Error: z.sml 38.20-38.26.
      Type cannot be shared (defined): T3.T4.t.
        type spec: type T3.T4.t = ?.a * a * T3.T4.c * c -> unit
        spec at: z.sml 8.12-8.12
    Error: z.sml 38.30-38.36.
      Type cannot be shared (defined): T5.T6.t.
        type spec: type T5.T6.t = ?.a * a * T5.T6.c * c -> unit
        spec at: z.sml 8.12-8.12

Now, the displayed type definition is relative to the environment at
the error point.  For "where type" signatures, a "_sig." prefix is
used for flexible type constructors that only exist in the signature
being realized; the contents of that signature are not in scope at the
error point, hence the "_sig." prefix.