Uniformly display unification notes in diagnostics
Consider the following program:

    structure S :
    sig
       type t
       val f : ('a * t) option -> (t * 'a) option
    end =
    struct
       val rf = ref NONE
       fun f z = (!rf before rf := z)
       datatype t = T
    end

    val (l, u) = ([], (fn () => ()) ())
    datatype t = T
    val z = T :: l

Now, MLton generates the following error messages:

    Error: z.sml 2.1-5.3.
      Variable in structure disagrees with signature (type): f.
        structure: val f: ([???] * [???]) option -> ([???] * [???]) option
        defn at:   z.sml 8.8-8.8
        signature: val f: (['a] * [_str.t]) option -> ([_str.t] * ['a]) option
        spec at:   z.sml 4.8-4.8
        note: type would escape the scope of its definition: _str.t
        note: type variable would not be generalized: 'a
    Error: z.sml 14.9-14.14.
      Constructor applied to incorrect argument.
        expects: _ * [t] list
        but got: _ * [???] list
        in: :: (T, l)
        note: type would escape the scope of its definition: t
    Warning: z.sml 7.8-7.9.
      Type of variable was not inferred and could not be generalized: rf.
        type: (??? * ???) option ref
        in: val rf = ref NONE
    Warning: z.sml 8.8-8.8.
      Type of variable was not inferred and could not be generalized: f.
        type: (??? * ???) option -> (??? * ???) option
        in: fun f z = (! rf before rf := z)
    Warning: z.sml 12.6-12.6.
      Type of variable was not inferred and could not be generalized: l.
        type: ??? list
        in: val (l, u) = ([], (fn () => ()) ())