MAIL bugfix for undefined reference to Real_{fetch,move,store}
Fixed bug in C codegen that would cause undefined references to
Real_{fetch,move,store} when compiling on Sparcs with -align 4.  The
problem was caused when we renamed the functions to
Real64_{fetch,move,store} in c-chunk.h but didn't keep up in the C
codegen.