Do not treat a record with only a #1 field as a tuple
Consider the following program:

    val l = [(true,1), {1 = true}]

    fun f r =
       case r of
          {1 = NONE} => ()

Previously, MLton generated the following messages:

    Error: r.sml 1.20-1.29.
      List with element of different type.
        element:  [bool]
        previous: [bool * int]
        in: [(true, 1), true]
    Warning: r.sml 5.7-5.22.
      Case is not exhaustive.
        missing pattern: (SOME _)
        in: case r of {1 = NONE} => ()

Note that the `{1: bool}` type and `{1 = SOME _}` pattern are
confusingly displayed as `bool` and `(SOME _)`.

Now, MLton generates the following messages:

    Error: r.sml 1.20-1.29.
      List with element of different type.
        element:  [{1: bool}]
        previous: [bool * int]
        in: [(true, 1), {1 = true}]
    Warning: r.sml 5.7-5.22.
      Case is not exhaustive.
        missing pattern: {1 = SOME _}
        in: case r of {1 = NONE} => ()