Fix minor bug with exception replication
An exception replication `exception <vid> = <longvid>` requires that
`<longvid>` have exception status, but MLton was allowing an
identifier with either (non-exn) constructor or exception status:

    exception E_NONE = NONE
    exception E_SOME = SOME

    fun f x =
       case x of
          E_NONE => ()
        | E_SOME () => ()

This program would compile without errors.  (Curiously, `E_NONE` and
`E_SOME` were added to the environment with exception status, but this
seems to have little effect on elaboration.)

Now, an exception replication properly checks that `<longvid>` has
exception status:

    Error: z.sml 1.20-1.23.
      Undefined exception: NONE.
    Error: z.sml 2.20-2.23.
      Undefined exception: SOME.
    Error: z.sml 7.7-7.12.
      Undefined constructor: E_SOME.