Set `prettyDefault: string` for flexible tycons
In very rare circumstances, a flexible tycon may be referenced (and
displayed in a diagnostic) but not in scope (and not have a pretty
name set).  For example, consider the following program:

    datatype a = A
    signature T =
       sig
          type a = a
          type b
          type c
          type d
          type t = a * b * c * d -> unit
       end
    signature S =
       sig
          type a
          type c
          structure T1:
             sig
                structure T2 :
                   sig
                      type a
                      include T where type b = a
                                where type d = c
                   end
             end where type T2.t = unit
       end

Previously, MLton generated the error messages:

    Error: z.sml 19.27-20.44.
      Duplicate type specification: a.
        spec at: z.sml 18.24-18.24
        spec at: z.sml 4.12-4.12
    Error: z.sml 22.25-22.28.
      Type cannot be realized (defined): T2.t.
        type spec: type T2.t = ?.a
                               * ?.{admitsEquality = Never,
                                    creationTime = 132,
                                    hasCons = false,
                                    id = 9238,
                                    kind = 0}
                               * _sig.T2.c
                               * c
                               -> unit
        spec at: z.sml 8.12-8.12

At the `where type T2.t = unit`, the `type a` of `T2` has been shadowed
by the `include T`, although the flexible tycon `b` of `T` has been
realized as the shadowed `a`.

Now, MLton generates the following error messages:

    Error: z.sml 19.27-20.44.
      Duplicate type specification: a.
        spec at: z.sml 18.24-18.24
        spec at: z.sml 4.12-4.12
    Error: z.sml 22.25-22.28.
      Type cannot be realized (defined): T2.t.
        type spec: type T2.t = ?.a * ??.a * _sig.T2.c * c -> unit
        spec at: z.sml 8.12-8.12

Like shadowed tycons, a shadowed flexible tycon is displayed with a
default name (the name of the AST tycon that introduced it) prefixed
with "??".