When required to conjure up a bogus type, do so at the appropriate arity.
This avoids both cascading type-errors and an Error.bug abort of
elaboration.

The following program demonstrates the cascading type-error;
uncommenting the 'where type' constraint demonstrates the Error.bug.

signature Z = sig type ('a, 'b) zzz end
functor cpZ (Arg : Z) : Z (* where type ('a, 'b) zzz = ('a, 'b) Arg.zzz *) = 
struct 
   open Arg
end
structure Z1 = struct datatype ('a, 'b) zzz = Z end
structure Z2 = cpZ(structure Arg = Z1)

Previously, this would yield:
[fluet@shadow temp]$ mlton z.sml
Error: z.sml 7.20.
  Type zzz in argument signature but not in structure.
Error: z.sml 2.25.
  Type zzz has arity n-ary in structure but arity 2 in signature.
compilation aborted: parseAndElaborate reported errors
[fluet@shadow temp]$ mlton z.sml 
Error: z.sml 7.20.
  Type zzz in argument signature but not in structure.
ElaborateEnv.transparentCut.handleType: Nary tycon

Now, this yields:
[fluet@shadow temp]$ ../mlton.svn.trunk/build/bin/mlton z.sml
Error: z.sml 7.20.
  Type zzz in argument signature but not in structure.
compilation aborted: parseAndElaborate reported errors
[fluet@shadow temp]$ ../mlton.svn.trunk/build/bin/mlton z.sml
Error: z.sml 7.20.
  Type zzz in argument signature but not in structure.
compilation aborted: parseAndElaborate reported errors



SVN r6047