MAIL interaction of elaboration controls and functor applications
Due to the re-elaboration of a functor body at the point of
application, elaboration control dependent type-errors might only
appear at the point of application, not at the point of definition.
For example, consider the following:

a.sml:
functor F_A () =
   struct
      val r = ref 0
      fun inc () = (r := !r + 1; !r)

      fun f x y =
	 (inc ()
	  ; x + y)

      datatype t = A | B | C | D
      fun g x =
	 case x of A => 1
   end

b.sml:
structure B_S = F_A ()

z.mlb:
$(SML_LIB)/basis/basis.mlb
ann "sequenceUnit true" "warnMatch false" in
  a.sml
end
ann "sequenceUnit true" "warnMatch true" in
  b.sml
end

The old behavior would produce:

bash-2.05b$ mlton-stable -stop tc z.mlb
Error: a.sml 7.4.
  Sequence expression not of type unit.
    type: [int]
    in: inc ()
Warning: a.sml 12.3.
  Case is not exhaustive.
    missing pattern: B | C | D
    in: case x of (A) => (1)
compilation aborted: elaborate reported errors

Notice that the errors are a bit misleading: they point to a.sml, but
a.sml was clearly elaborated in a context with sequenceUnit false and
warnMatch false.  We can confirm that it is due to the re-elaboration
in b.sml by commenting out b.sml from the .mlb:

z.mlb:
$(SML_LIB)/basis/basis.mlb
ann "sequenceUnit true" "warnMatch false" in
  a.sml
end
ann "sequenceUnit true" "warnMatch true" in
  (* b.sml *)
end

The new behavior is to snapshot the state of the elaboration controls
at the point of functor definition and (temporarily) reinstate those
controls for each application (i.e., re-elaboration of the body).
I think this is a more intuitive behavior.