Fix "type in str disagrees with sig (admits equality)" diagnostics
Consider the following program:

    structure S :
    sig
       eqtype t
       eqtype ('a, 'b) u
    end =
    struct
       type t = real
       type ('a, 'b) u = 'a -> 'b
    end

Previously, MLton gave the following error messages:

    Error: z.sml 2.1-5.3.
      Type in structure disagrees with signature (admits equality): t.
        structure: type t = [real64]
        defn at:   z.sml 7.9-7.9
        signature: [eqtype] t
        spec at:   z.sml 3.11-3.11
    Error: z.sml 2.1-5.3.
      Type in structure disagrees with signature (admits equality): u.
        structure: type ('a, 'b) u = [arrow]
        defn at:   z.sml 8.18-8.18
        signature: [eqtype] ('a, 'b) u
        spec at:   z.sml 4.20-4.20

Note that the types from the structure are not printed with pretty
type constructor applications.

Now, MLton gives the following error messages:

    Error: z.sml 2.1-5.3.
      Type in structure disagrees with signature (admits equality): t.
        structure: type t = [t]
        defn at:   z.sml 7.9-7.9
        signature: [eqtype] t
        spec at:   z.sml 3.11-3.11
    Error: z.sml 2.1-5.3.
      Type in structure disagrees with signature (admits equality): u.
        structure: type ('a, 'b) u = [_ -> _]
        defn at:   z.sml 8.18-8.18
        signature: [eqtype] ('a, 'b) u
        spec at:   z.sml 4.20-4.20

The incongruous "type t = [t]" is due to the choice of tycon to
represent the "real32" type, because tycon names are chosen with the
strexp being constrained in scope.