Avoid a spurious error caused by type definitions missing in structures.  For example,
structure S:
   sig
      datatype value = V
      datatype t = T of value
   end =
   struct
      datatype t = T
   end

causes the spurious error

Error: z.sml 2.4.
  Type t has arity 0 in structure but arity n-ary in signature.

After this checkin, that message is gone.