Set more informative `prettyDefault: string` for flexible tycons
Consider the following program:

    structure A =
       struct
          datatype a = A
          structure B =
             struct
                datatype b = B
             end
          val b = B.B
          structure B = struct end
          val _ : unit = b
       end
    signature T =
       sig
          type a = A.a
          type b
          type c
          type d
          type t = a * b * c * d -> unit
       end
    structure A = struct end
    signature S =
       sig
          type a
          type c
          structure T1:
             sig
                structure T2 :
                   sig
                      type a
                      include T where type b = a
                                where type d = c
                   end
             end where type T2.t = unit
       end

Now, MLton generates the following error messages:

    Error: z.sml 10.11-10.22.
      Pattern and expression disagree.
        pattern:    [unit]
        expression: [?.A.B.b]
        in: val _: unit = b
    Error: z.sml 30.27-31.44.
      Duplicate type specification: a.
        spec at: z.sml 29.24-29.24
        spec at: z.sml 14.12-14.12
    Error: z.sml 33.25-33.28.
      Type cannot be realized (defined): T2.t.
        type spec: type T2.t = ?.A.a * ??.S.T1.T2.a * _sig.T2.c * c -> unit
        spec at: z.sml 18.12-18.12

Note in the first error message that the default pretty name for a
shadowed tycon includes the structure in which it is being defined.
Now, in the last error message, the default pretty name for a flexible
tycon includes the signature in which it is being defined.
Previously, the last error message had "??.a" instead of
"??.S.T1.T2.a".