Fixed a bug in front end error message.  The problem was in reporting the error for a type used before its definition.  The error message attempts to display the point of definition of the type. Unfortunately the front end only tracked the point of definition for datatypes.  I changed it so that it now tracks it for tycons declared by type declarations as well.
The following example tickles the bug in MLton 20041109.

------------------------------------------------------------
val r = ref NONE
functor F (type t
	   val x: t) =
   struct
      val () = r := SOME x
      fun get () = valOf (!r)
   end
structure S1 = F (type t = unit -> unit
		  val x = fn () => ())
structure S2 = F (type t = int
		  val x = 13)
val () = S1.get () ()
------------------------------------------------------------

MLton 20041109 prints a warning and then dies with a bug.

------------------------------------------------------------
Warning: z.sml 1.1.
  Unable to locally determine type of variable: r.
    type: ??? option ref
    in: val r = ref NONE
t has no region property
------------------------------------------------------------

After this bug fix, MLton now prints the following.

------------------------------------------------------------
Warning: z.sml 1.1.
  Unable to locally determine type of variable: r.
    type: ??? option ref
    in: val r = ref NONE
Error: z.sml 1.1.
  Type escapes the scope of its definition at z.sml 2.17.
    type: t
    in: val r = ref NONE
------------------------------------------------------------