Represent parenthesized expressions in AST
Explicitly representing parenthesized expressions in the AST allows
for more accurate region information.  Consider the following
ill-typed program:

   val _ = (  if true then 1 else #"c"  ) ()

Previously, the parenthesized if expression would be re-wrapped with
the region of the parentheses, yielding the messages:

    Error: dec.sml 1.9-1.38.
      Then and else branches disagree.
        then: [int]
        else: [char]
        in: if true then 1 else #"a"
    Error: dec.sml 1.9-1.41.
      Function not of arrow type.
        function: [int]
        in: (if true then 1 else #"a") ()

Now, the if expression retains its original region, when the
paren expression receives its own region, which is incorporated into
the region of the application expression, yielding the messages:

    Error: dec.sml 1.12-1.35.
      Then and else branches disagree.
        then: [int]
        else: [char]
        in: if true then 1 else #"a"
    Error: dec.sml 1.9-1.41.
      Function not of arrow type.
        function: [int]
        in: (if true then 1 else #"a") ()