Update diagnostics for val rec declarations
Consider the following program:

   val rec f1 = fn z => if z <= 0 then 1 else g1 (z - 1)
       and g1 = fn z => if z <= 0 then false else f1 (z - 1)

Previously, MLton generated the following error messages:

    Error: z.sml 2.22-2.57.
      Then and else branches disagree.
        then: [bool]
        else: [int]
        in: if z <= 0 then false else f1 (z - 1)
    Error: z.sml 2.9-2.57.
      Recursive function pattern and expression disagree.
        pattern:    _ -> [int]
        expression: _ -> [bool]
        in: val rec f1 = fn z => (if z <= 0 t  ...  lse else f1 (z - 1))
    Error: z.sml 4.5-4.6.
      Recursive use of function disagrees with function declaration type: f2.
        recursive use: _ -> [bool]
        function type: _ -> [int]
        in: fun f2 z = (if z <= 0 then 1 else  ...  lse else f2 (z - 1))
    Error: z.sml 5.5-5.6.
      Recursive use of function disagrees with function declaration type: g2.
        recursive use: _ -> [int]
        function type: _ -> [bool]
        in: fun f2 z = (if z <= 0 then 1 else  ...  lse else f2 (z - 1))

There is a bit of asymmetry, due to `g1` being constrained to the type
`int -> int` by the `g1 (z - 1)` in the function body of `f1` and `f1`
being constrained to the type `int -> int` by the function expression
of `f1`, all before processing the function expression and binding of
`g1`.  Contrast with the handling of the `fun` version, which gives
symmetric errors by delaying the unification of the function variables
with their inferred function types until all functions have been
processed.

Now, MLton generates the following error messages:

    Error: z.sml 1.9-1.10.
      Recursive use of function disagrees with function expression type: f1.
        recursive use: _ -> [bool]
        function type: _ -> [int]
        in: val rec f1 = fn z => (if z <= 0 t  ...  lse else f1 (z - 1))
    Error: z.sml 2.9-2.10.
      Recursive use of function disagrees with function expression type: g1.
        recursive use: _ -> [int]
        function type: _ -> [bool]
        in: val rec f1 = fn z => (if z <= 0 t  ...  lse else f1 (z - 1))
    Error: z.sml 4.5-4.6.
      Recursive use of function disagrees with function declaration type: f2.
        recursive use: _ -> [bool]
        function type: _ -> [int]
        in: fun f2 z = (if z <= 0 then 1 else  ...  lse else f2 (z - 1))
    Error: z.sml 5.5-5.6.
      Recursive use of function disagrees with function declaration type: g2.
        recursive use: _ -> [int]
        function type: _ -> [bool]
        in: fun f2 z = (if z <= 0 then 1 else  ...  lse else f2 (z - 1))

Adding explicit type annotations:

    val rec f1 : int -> int = fn z => if z <= 0 then 1 else g1 (z - 1)
        and g1 : int -> int = fn z => if z <= 0 then false else f1 (z - 1)

adjusts the error messages:

    Error: z.sml 2.35-2.70.
      Then and else branches disagree.
        then: [bool]
        else: [int]
        in: if z <= 0 then false else f1 (z - 1)
    Error: z.sml 2.9-2.70.
      Recursive function pattern and expression disagree.
        pattern:    _ -> [int]
        expression: _ -> [bool]
        in: val rec f1: (int -> int) = fn z =  ...  lse else f1 (z - 1))