Improve time-based diagnostics
Consider the following program:

    val (l, u) = ([], (fn () => ()) ())
    datatype t = T
    val _ = (SOME T, SOME (T, T)) :: l

    val rf = ref NONE
    val 'a f: 'a option -> 'a option =
       fn z => (!rf before rf := z)

    structure S:
    sig
       val f: 'a option -> 'a option
    end =
    struct
       val rf = ref NONE
       fun f z = (!rf before rf := z)
    end

Previously, MLton generated the following error messages:

    Error: z.sml 1.1-1.35.
      Type escapes the scope of its definition: t.
        defn at: z.sml 2.10-2.10
        in: val (l, u) = ([], (fn () => ()) ())
    Error: z.sml 6.1-7.31.
      Type variable cannot be bound at declaration: 'a.
        in: val 'a f: ('a option -> 'a option  ...  ! rf before rf := z)
    Error: z.sml 10.1-12.3.
      Variable in structure disagrees with signature: f.
        structure: 'a cannot be generalized
        defn at:   z.sml 15.8-15.8
        signature: 'a option -> 'a option
        spec at:   z.sml 11.8-11.8

A difficulty with understanding these errors is that they point to a
declaration, but the error is due to some unification occurring in an
expression.

Now, MLton generates the following error messages:

    Error: z.sml 3.9-3.34.
      Constructor applied to incorrect argument.
        expects: _ * ([t] option * ([t] * [t]) option) list
        but got: _ * ([???] option * ([???] * [???]) option) list
        in: :: ((SOME T, SOME (T, T)), l)
    Error: z.sml 6.8-7.31.
      Pattern and expression disagree.
        pattern:    ['a] option -> ['a] option
        expression: [???] option -> [???] option
        in: val 'a f: ('a option -> 'a option  ...  ! rf before rf := z)
    Error: z.sml 10.1-12.3.
      Variable in structure disagrees with signature: f.
        structure: [???] option -> [???] option
        defn at:   z.sml 15.8-15.8
        signature: ['a] option -> ['a] option
        spec at:   z.sml 11.8-11.8
    Warning: z.sml 1.6-1.6.
      Unable to locally determine type of variable: l.
        type: (??? option * (??? * ???) option) list
        in: val (l, u) = ([], (fn () => ()) ())
    Warning: z.sml 5.5-5.6.
      Unable to locally determine type of variable: rf.
        type: ??? option ref
        in: val rf = ref NONE
    Warning: z.sml 14.8-14.9.
      Unable to locally determine type of variable: rf.
        type: ??? option ref
        in: val rf = ref NONE
    Warning: z.sml 15.8-15.8.
      Unable to locally determine type of variable: f.
        type: ??? option -> ??? option
        in: fun f z = (! rf before rf := z)

The implementation builds on the `checkTime` function from the
previous commit.  When a unification variable is unified with a type,
a `checkTime` (rather than a `minTime`) is performed; if the time
check fails, then the unification variable is replaced by the
alternate type (which effectively, pushes the unification variable
down through the type to the points of the violation).  The various
`minTime` calls with respect to flexible records are eliminated by
first ensuring that the flexible record has all of the necessary
fields (created with fresh unification variables at the time of of the
flexible record, if necessary).  This has the added benefit of
simplifying the unification of records, since it is not responsible
for adding fields.