Use literal text for constants in error messages
Carry the exact (literal) text used for constants (literals) from lexer through
to elaboration, so that error message using the constants appear as they are
written in the source file.

Consider the program (with type errors):

    val _ = "a甲\010" ^ (Substring.full "b乙\n")
    val _ : word = 0xabcd
    val _ : string = "abc\uaBcD\UAbCdEf00xyz"

Previously, the error messages were:

    Error: z.sml 1.9-1.46.
      Function applied to incorrect argument.
        expects: _ * [string]
        but got: _ * [char VectorSlice.slice]
        in: ^ ("a\231\148\178\n", Substring.full "b\228\185\153\n")
    Error: z.sml 2.5-2.21.
      Pattern and expression disagree.
        pattern:    [word]
        expression: [int]
        in: val _: word = 43981
    Error: z.sml 3.18-3.41.
      String constant with characters too large for type: #"\uABCD", #"\UABCDEF00".
        type: string

Now, the error messages are:

    Error: z.sml 1.9-1.46.
      Function applied to incorrect argument.
        expects: _ * [string]
        but got: _ * [char VectorSlice.slice]
        in: ^ ("a甲\010", Substring.full "b乙\n")
    Error: z.sml 2.5-2.21.
      Pattern and expression disagree.
        pattern:    [word]
        expression: [int]
        in: val _: word = 0xabcd
    Error: z.sml 3.18-3.41.
      String constant with characters too large for type: #"\uaBcD", #"\UAbCdEf00".
        type: string
        in: "abc\uaBcD\UAbCdEf00xyz"

Closes MLton/mlton#517