Create dummy tycon with name prefixed by structure being defined
Consider the following program:

    structure S :
    sig
       eqtype t
       val toString: t -> string
    end =
    struct
       type t = real
       val toString = Real.toString
    end
    val toString = S.toString
    structure S = struct end
    val _ = toString ()

Previously, MLton generated the following error message:

    Error: z.sml 2.1-5.3.
      Type in structure disagrees with signature (admits equality): t.
        structure: type t = [real]
        defn at:   z.sml 7.9-7.9
        signature: [eqtype] t
        spec at:   z.sml 3.11-3.11
    Error: z.sml 2.1-5.3.
      Variable in structure disagrees with signature: toString.
        structure: [real] -> _
        defn at:   z.sml 8.8-8.15
        signature: [_sig.t] -> _
        spec at:   z.sml 4.8-4.15
    Error: z.sml 12.9-12.19.
      Function applied to incorrect argument.
        expects: [?.t]
        but got: [unit]
        in: toString ()

Note that the final error message is in terms of the `?.t` type.  The
`?` is correct, because the type is not in scope.  However, it would
be more proper to name it `?.S.t`, indicating it is from a shadowed
`S.t`.