Propagate equality status to unknowns generated for flexible records
Consider the following program:

    fun f (x: ''a) = ()

    fun g (r1 as {...}) =
       let
          val _ = f r1
          val _ : {x: real, y: unit, z: unit -> unit} = r1
       in
          ()
       end

    fun g (r1 as {...}) =
       let
          val _ : {x: real, y: unit, z: unit -> unit} = r1
          val _ = f r1
       in
          ()
       end

    fun g (r1 as {x,y,z}) =
       let
          val _ = f r1
          val _ : {x: real, y: unit, z: unit -> unit} = r1
       in
          ()
       end

    fun g (r1 as {x,y,z}) =
       let
          val _ : {x: real, y: unit, z: unit -> unit} = r1
          val _ = f r1
       in
          ()
       end

Previously, MLton generated the following error messages:

    Error: z.sml 6.11-6.54.
      Pattern and expression disagree.
        pattern:    {x: [real], z: [_ -> _], ...}
        expression: [<equality>]
        in: val _: {x: real, y: unit, z: (unit -> unit)} = r1
    Error: z.sml 14.15-14.18.
      Function applied to incorrect argument.
        expects: [<equality>]
        but got: {x: [real], z: [_ -> _], ...}
        in: f r1
    Error: z.sml 22.11-22.54.
      Pattern and expression disagree.
        pattern:    {x: [real], z: [_ -> _], ...}
        expression: {x: [<equality>], z: [<equality>], ...}
        in: val _: {x: real, y: unit, z: (unit -> unit)} = r1
    Error: z.sml 30.15-30.18.
      Function applied to incorrect argument.
        expects: [<equality>]
        but got: {x: [real], z: [_ -> _], ...}
        in: f r1

Note the asymmetry in the "Pattern and expression disagree" messages.
Now, MLton generates the following error message:

    Error: z.sml 6.11-6.54.
      Pattern and expression disagree.
        pattern:    {x: [real], z: [_ -> _], ...}
        expression: {x: [<equality>], z: [<equality>], ...}
        in: val _: {x: real, y: unit, z: (unit -> unit)} = r1
    Error: z.sml 14.15-14.18.
      Function applied to incorrect argument.
        expects: [<equality>]
        but got: {x: [real], z: [_ -> _], ...}
        in: f r1
    Error: z.sml 22.11-22.54.
      Pattern and expression disagree.
        pattern:    {x: [real], z: [_ -> _], ...}
        expression: {x: [<equality>], z: [<equality>], ...}
        in: val _: {x: real, y: unit, z: (unit -> unit)} = r1
    Error: z.sml 30.15-30.18.
      Function applied to incorrect argument.
        expects: [<equality>]
        but got: {x: [real], z: [_ -> _], ...}
        in: f r1

It should be the case that the only equality status mismatches now
occur between an Unknown and a type.