Record and report origin of flexible tycon specs
Consider the following program:

    signature T =
       sig
          type t
       end
    signature Z = T where type t = bool
    signature P =
       sig
          structure T1 : T
          structure T2 : T
          structure T3 : T
          sharing type T1.t = T2.t
          sharing type T2.t = T3.t
       end
    signature Q =
       sig
          structure T1 : T
          structure T2 : T
          sharing T1 = T2
       end

    structure Z : Z =
       struct
          datatype t = T of bool
       end
    structure P : P =
       struct
          structure T1 =
             struct
                datatype t = T
             end
          structure T2 =
             struct
                type t = T1.t
             end
          structure T3 =
             struct
                datatype t = T
             end
       end
    structure Q : Q =
       struct
          structure T1 =
             struct
                datatype t = T
             end
          structure T2 =
             struct
                datatype t = T
             end
       end

Previously, MLton generated the following error messages:

    Error: z.sml 21.15-21.15.
      Type in structure disagrees with signature (type structure): t.
        structure: [datatype] t = ...
        defn at:   z.sml 23.16-23.16
        signature: [type] t = bool
        spec at:   z.sml 3.12-3.12
    Error: z.sml 25.15-25.15.
      Type in structure disagrees with signature (type structure): T3.t.
        structure: [datatype] T3.t = ...
        defn at:   z.sml 37.22-37.22
        signature: [type] T3.t = T2.t
        spec at:   z.sml 3.12-3.12
    Error: z.sml 40.15-40.15.
      Type in structure disagrees with signature (type structure): T2.t.
        structure: [datatype] T2.t = ...
        defn at:   z.sml 48.22-48.22
        signature: [type] T2.t = T1.t
        spec at:   z.sml 3.12-3.12

Each error notes that the type t specified by the signature must be
equal to a particular type; however, the "spec at:" location is the
"type t" in "signature T", which does not provide insight into the
origin of the restriction on "type t".  In particular, if the binding
occurence of the type in a signature is in one file but the `where` or
`sharing` refinement is in another file, then the "spec at:" location
can be especially confusing.

Now, MLton generates the following error messages:

    Error: z.sml 21.15-21.15.
      Type in structure disagrees with signature (type structure): t.
        structure: [datatype] t = ...
        defn at:   z.sml 23.16-23.16
        signature: [type] t = bool
        spec at:   z.sml 3.12-3.12
        spec at:   z.sml 5.28-5.35
    Error: z.sml 25.15-25.15.
      Type in structure disagrees with signature (type structure): T3.t.
        structure: [datatype] T3.t = ...
        defn at:   z.sml 37.22-37.22
        signature: [type] T3.t = T2.t
        spec at:   z.sml 3.12-3.12
        spec at:   z.sml 11.7-11.30
        spec at:   z.sml 12.7-12.30
    Error: z.sml 40.15-40.15.
      Type in structure disagrees with signature (type structure): T2.t.
        structure: [datatype] T2.t = ...
        defn at:   z.sml 48.22-48.22
        signature: [type] T2.t = T1.t
        spec at:   z.sml 3.12-3.12
        spec at:   z.sml 18.7-18.21

At each refinement of a flexible type constructor due to a `where` or
`sharing` clause, the region of that specification is added, to be
included in the diganostics.