Improve "equality in signature but not in structure" diagnostics
Consider the following program:

    structure S :
       sig
          eqtype t
          eqtype 'a u
          eqtype v
       end =
    struct
       datatype t = T1 of real | T2 of real | T3 of unit
       type 'a u = 'a * real
       type v = real
    end

Previously, the following error messages were generated:

    Error: z.sml 2.4-6.6.
      Type t admits equality in signature but not in structure.
        not equality: T1 of [v]
                      T2 of [v]
    Error: z.sml 2.4-6.6.
      Type u admits equality in signature but not in structure.
        not equality: ['a] * [v]
    Error: z.sml 2.4-6.6.
      Type v admits equality in signature but not in structure.
        not equality: v

Now, the following error messages are generated:

    Error: z.sml 2.4-6.6.
      Type t admits equality in signature but not in structure.
        not equality: T1 of [v] | T2 of [v] | ...
    Error: z.sml 2.4-6.6.
      Type u admits equality in signature but not in structure.
        not equality: _ * [v]
    Error: z.sml 2.4-6.6.
      Type v admits equality in signature but not in structure.
        not equality: [v]

Unfortunately, the choice of `v` to represent the type `real` is
due to setting the type constructor print names in the context of
the structure being matched.