Improve "type cannot be {shared,realized}" diagnostics
Show the definition of a type specification that cannot be shared or
realized due to not being a flexible tycon.  For instance, consider
the following program:

    datatype a = A

    signature T =
       sig
          type b
          type s
          type u
          type t = u * s * b -> a
       end
    signature S =
       sig
          type a
          type s
          structure T1: T where type b = a where type s = s
                          where type t = unit
          structure T2: T where type b = a where type s = s
          structure T3: T where type b = a where type s = s
          sharing T2 = T3
       end

Previously, MLton generated the following error messages:

    Error: z.sml 15.34-15.34.
      Type cannot be realized (defined): t.
        type spec: type t = [...]
        spec at: z.sml 8.12-8.12
    Error: z.sml 18.20-18.21.
      Type cannot be shared (defined): T3.t.
        type spec: type T3.t = [...]
        spec at: z.sml 8.12-8.12
    Error: z.sml 18.15-18.16.
      Type cannot be shared (defined): T2.t.
        type spec: type T2.t = [...]
        spec at: z.sml 8.12-8.12

Now, MLton generates the following error messages:

    Error: z.sml 15.34-15.34.
      Type cannot be realized (defined): t.
        type spec: type t = _sig.T1.u * _sig.s * _sig.a -> a
        spec at: z.sml 8.12-8.12
    Error: z.sml 18.15-18.16.
      Type cannot be shared (defined): T2.t.
        type spec: type T2.t = _sig.T2.u * _sig.s * _sig.a -> a
        spec at: z.sml 8.12-8.12
    Error: z.sml 18.20-18.21.
      Type cannot be shared (defined): T3.t.
        type spec: type T3.t = _sig.T3.u * _sig.s * _sig.a -> a
        spec at: z.sml 8.12-8.12

Note that all flexible tycons of the top-level signature are displayed
as "_sig.*", which necessarily disambiguates them from tycons coming
from the environment.