Improve "Type in signature but not in structure" diagnostics
Consider the following program:

    signature T = sig datatype t = T1 | T2 of bool end
    structure S : sig
      include T
      structure U: sig
         datatype t = datatype t
      end
      structure V: T where type t = t
      structure W: T
      sharing type t = W.t
    end = struct
      structure U = struct end
      structure V = struct end
      structure W = struct end
    end

Previously, MLton generated the following error messags:

    Error: z.sml 2.15-10.3.
      Type in signature but not in structure: U.t.
        signature: datatype t = T1 | T2 of bool
        spec at:   z.sml 5.15-5.15
        spec at:   z.sml 7.18-7.33
        spec at:   z.sml 9.3-9.22
    Error: z.sml 2.15-10.3.
      Type in signature but not in structure: V.t.
        signature: datatype t = T1 | T2 of bool
        spec at:   z.sml 1.28-1.28
        spec at:   z.sml 7.18-7.33
        spec at:   z.sml 9.3-9.22
    Error: z.sml 2.15-10.3.
      Type in signature but not in structure: W.t.
        signature: datatype t = T1 | T2 of bool
        spec at:   z.sml 1.28-1.28
        spec at:   z.sml 7.18-7.33
        spec at:   z.sml 9.3-9.22
    Error: z.sml 2.15-10.3.
      Type in signature but not in structure: t.
        signature: datatype t = T1 | T2 of bool
        spec at:   z.sml 1.28-1.28
        spec at:   z.sml 7.18-7.33
        spec at:   z.sml 9.3-9.22

These message obsure the fact that all of the datatypes are required
to be the same type structure.  Now, MLton generates the following
error messages:

    Error: z.sml 2.15-10.3.
      Type in signature but not in structure: U.t.
        signature: datatype U.t = datatype _sig.t
        spec at:   z.sml 5.15-5.15
        spec at:   z.sml 7.18-7.33
        spec at:   z.sml 9.3-9.22
    Error: z.sml 2.15-10.3.
      Type in signature but not in structure: V.t.
        signature: datatype V.t = datatype _sig.t
        spec at:   z.sml 1.28-1.28
        spec at:   z.sml 7.18-7.33
        spec at:   z.sml 9.3-9.22
    Error: z.sml 2.15-10.3.
      Type in signature but not in structure: W.t.
        signature: datatype W.t = datatype _sig.t
        spec at:   z.sml 1.28-1.28
        spec at:   z.sml 7.18-7.33
        spec at:   z.sml 9.3-9.22
    Error: z.sml 2.15-10.3.
      Type in signature but not in structure: t.
        signature: datatype t = T1 | T2 of bool
        spec at:   z.sml 1.28-1.28
        spec at:   z.sml 7.18-7.33
        spec at:   z.sml 9.3-9.22

Only the type constructor chosen as the flexible represenative is
shown with constructors; the other type constructors are shown as
datatype replications.