Track datatype replication in specifications
Consider the following program:

    structure S : sig
      structure U: sig datatype u = U end
      datatype t = datatype U.u

      structure V: sig type v end
      datatype w = datatype V.v

      structure Y: sig type y end
      type z = Y.y
    end = struct
      structure U = struct end
      structure V = struct end
      structure Y = struct end
    end

Previously, MLton generated the following error messages:

    Error: z.sml 1.15-10.3.
      Type in signature but not in structure: U.u.
        signature: datatype U.u = datatype _sig.t
        spec at:   z.sml 2.29-2.29
        spec at:   z.sml 3.25-3.27
    Error: z.sml 1.15-10.3.
      Type in signature but not in structure: V.v.
        signature: type V.v = _sig.w
        spec at:   z.sml 5.25-5.25
        spec at:   z.sml 6.25-6.27
    Error: z.sml 1.15-10.3.
      Type in signature but not in structure: Y.y.
        signature: type Y.y
        spec at:   z.sml 8.25-8.25
        spec at:   z.sml 9.12-9.14
    Error: z.sml 1.15-10.3.
      Type in signature but not in structure: t.
        signature: datatype t = U
        spec at:   z.sml 3.12-3.12
        spec at:   z.sml 3.25-3.27
    Error: z.sml 1.15-10.3.
      Type in signature but not in structure: w.
        signature: type w
        spec at:   z.sml 6.12-6.12
        spec at:   z.sml 6.25-6.27
    Error: z.sml 1.15-10.3.
      Type in signature but not in structure: z.
        signature: type z = _sig.Y.y
        spec at:   z.sml 9.8-9.8
        spec at:   z.sml 9.12-9.14

Note that `t` and `w` were chosen as the representative flexible
tycons to be realized, although both are specified as datatype
replications, while the display signature specifications for `U.u` and
`V.v` show them defined in terms of `t` and `w`.  In contrast, `z` is
not chosen as a representative flexible tycon to be realized, because
it is specified as a type bind.

Now, MLton generates the following error messages:

    Error: z.sml 1.15-10.3.
      Type in signature but not in structure: U.u.
        signature: datatype U.u = U
        spec at:   z.sml 2.29-2.29
        spec at:   z.sml 3.25-3.27
    Error: z.sml 1.15-10.3.
      Type in signature but not in structure: V.v.
        signature: type V.v
        spec at:   z.sml 5.25-5.25
        spec at:   z.sml 6.25-6.27
    Error: z.sml 1.15-10.3.
      Type in signature but not in structure: Y.y.
        signature: type Y.y
        spec at:   z.sml 8.25-8.25
        spec at:   z.sml 9.12-9.14
    Error: z.sml 1.15-10.3.
      Type in signature but not in structure: t.
        signature: datatype t = datatype _sig.U.u
        spec at:   z.sml 3.12-3.12
        spec at:   z.sml 3.25-3.27
    Error: z.sml 1.15-10.3.
      Type in signature but not in structure: w.
        signature: type w = _sig.V.v
        spec at:   z.sml 6.12-6.12
        spec at:   z.sml 6.25-6.27
    Error: z.sml 1.15-10.3.
      Type in signature but not in structure: z.
        signature: type z = _sig.Y.y
        spec at:   z.sml 9.8-9.8
        spec at:   z.sml 9.12-9.14

The choice of representative flexible tycons to be realized does not
choose a datatype replication.