Better diagnostics with explicit type variables
Consider the following program:

    fun f (x: 'x, y: 'y) = (x : 'a, y : 'b)

Previously, MLton generated the following error messages:

    Error: z.sml 1.25-1.30.
      Expression and constraint disagree.
        expression: ['a]
        constraint: ['b]
        in: x: 'a
    Error: z.sml 1.33-1.38.
      Expression and constraint disagree.
        expression: ['a]
        constraint: ['b]
        in: y: 'b

The generated type variable names in the unification-error diagnostics
confusingly conflict with the explicit type variables in the source.

Now, MLton generates the following error messages:

    Error: z.sml 1.25-1.30.
      Expression and constraint disagree.
        expression: ['x]
        constraint: ['a]
        in: x: 'a
    Error: z.sml 1.33-1.38.
      Expression and constraint disagree.
        expression: ['y]
        constraint: ['b]
        in: y: 'b