Updates "<thing> in signature but not in structure" diagnostics
Consider the following program:

    signature T =
       sig
          type t
          val toString: t -> string
          structure U:
             sig
                datatype u = C of unit
                val toString: u -> string
             end
       end
    structure S:
       sig
          include T
          structure T1: T
          structure T2: T where type t = T1.t
                          where type U.u = T1.U.u
          structure T3: T
          structure T4: T
          sharing type T3.t = T4.t
          sharing type T3.U.u = T4.U.u
          structure Z:
             sig
                structure Z1:
                   sig
                      datatype z = C of unit
                   end
                structure Z2:
                   sig
                      datatype z = datatype U.u
                   end
                structure Z3:
                   sig
                      datatype z = C of unit
                   end where type z = U.u
                structure Z4:
                   sig
                      datatype z = C of unit
                   end
             end
          sharing type Z.Z4.z = U.u
       end =
    struct
       structure Z = struct end
    end

    functor TIO(structure TIO: TEXT_IO) = struct end
    structure TIO = TIO(struct end)
    signature TEXT_IO = sig end
    signature TEXT_STREAM_IO = sig end
    structure TIO = TIO(struct end)

Previously, MLton gave the following error messages:

    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: T1.
        signature: structure T1: T
                                 where type U.u = _sig.T1.U.u
                                 where type t = _sig.T1.t
        spec at:   z.sml 14.17-14.18
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: T2.
        signature: structure T2: T
                                 where type U.u = _sig.T1.U.u
                                 where type t = _sig.T1.t
        spec at:   z.sml 15.17-15.18
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: T3.
        signature: structure T3: T
                                 where type U.u = _sig.T3.U.u
                                 where type t = _sig.T3.t
        spec at:   z.sml 17.17-17.18
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: T4.
        signature: structure T4: T
                                 where type U.u = _sig.T3.U.u
                                 where type t = _sig.T3.t
        spec at:   z.sml 18.17-18.18
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: U.
        signature: structure U:
                      sig
                         datatype u = C of unit
                         val toString: _sig.U.u -> string
                      end
        spec at:   z.sml 5.17-5.17
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: Z.Z1.
        signature: structure Z1:
                      sig
                         datatype z = C of unit
                      end
        spec at:   z.sml 23.23-23.24
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: Z.Z2.
        signature: structure Z2:
                      sig
                         datatype z = C of unit
                      end
        spec at:   z.sml 27.23-27.24
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: Z.Z3.
        signature: structure Z3:
                      sig
                         datatype z = C of unit
                      end
        spec at:   z.sml 31.23-31.24
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: Z.Z4.
        signature: structure Z4:
                      sig
                         datatype z = C of unit
                      end
        spec at:   z.sml 35.23-35.24
    Error: z.sml 12.4-41.6.
      Type in signature but not in structure: t.
        signature: type t
        spec at:   z.sml 3.12-3.12
    Error: z.sml 12.4-41.6.
      Variable in signature but not in structure: toString.
        signature: val toString: _sig.t -> string
        spec at:   z.sml 4.11-4.18
    Error: z.sml 47.17-47.31.
      Structure in argument signature but not in structure: TIO.
        signature: structure TIO: TEXT_IO
                                  where type StreamIO.instream = _sig.TIO.StreamIO.instream
                                  where type StreamIO.out_pos = _sig.TIO.StreamIO.out_pos
                                  where type StreamIO.outstream = _sig.TIO.StreamIO.outstream
                                  where type instream = _sig.TIO.instream
                                  where type outstream = _sig.TIO.outstream
        spec at:   z.sml 46.23-46.25
    Error: z.sml 50.17-50.31.
      Structure in argument signature but not in structure: TIO.
        signature: structure TIO:
                      sig
                         type elem = char
                         type instream = _sig.TIO.instream
                         type outstream = _sig.TIO.outstream
                         type vector = string
                         val canInput: _sig.TIO.instream * int -> int option
                         val closeIn: _sig.TIO.instream -> unit
                         val closeOut: _sig.TIO.outstream -> unit
                         val endOfStream: _sig.TIO.instream -> bool
                         val flushOut: _sig.TIO.outstream -> unit
                         val getInstream: _sig.TIO.instream
                                          -> _sig.TIO.StreamIO.instream
                         val getOutstream: _sig.TIO.outstream
                                           -> _sig.TIO.StreamIO.outstream
                         val getPosOut: _sig.TIO.outstream
                                        -> _sig.TIO.StreamIO.out_pos
                         val input: _sig.TIO.instream -> string
                         val input1: _sig.TIO.instream -> char option
                         val inputAll: _sig.TIO.instream -> string
                         val inputLine: _sig.TIO.instream -> string option
                         val inputN: _sig.TIO.instream * int -> string
                         val lookahead: _sig.TIO.instream -> char option
                         val mkInstream: _sig.TIO.StreamIO.instream
                                         -> _sig.TIO.instream
                         val mkOutstream: _sig.TIO.StreamIO.outstream
                                          -> _sig.TIO.outstream
                         val openAppend: string -> _sig.TIO.outstream
                         val openIn: string -> _sig.TIO.instream
                         val openOut: string -> _sig.TIO.outstream
                         val openString: string -> _sig.TIO.instream
                         val output: _sig.TIO.outstream * string -> unit
                         val output1: _sig.TIO.outstream * char -> unit
                         val outputSubstr: _sig.TIO.outstream
                                           * char VectorSlice.slice
                                           -> unit
                         val print: string -> unit
                         val scanStream: ((_sig.TIO.StreamIO.instream
                                           -> (char * _sig.TIO.StreamIO.instream) option)
                                          -> _sig.TIO.StreamIO.instream
                                             -> ('a * _sig.TIO.StreamIO.instream) option)
                                         -> _sig.TIO.instream -> 'a option
                         val setInstream: _sig.TIO.instream
                                          * _sig.TIO.StreamIO.instream
                                          -> unit
                         val setOutstream: _sig.TIO.outstream
                                           * _sig.TIO.StreamIO.outstream
                                           -> unit
                         val setPosOut: _sig.TIO.outstream
                                        * _sig.TIO.StreamIO.out_pos
                                        -> unit
                         val stdErr: _sig.TIO.outstream
                         val stdIn: _sig.TIO.instream
                         val stdOut: _sig.TIO.outstream
                         structure StreamIO:
                            sig
                               type elem = char
                               type instream = _sig.TIO.StreamIO.instream
                               type out_pos = _sig.TIO.StreamIO.out_pos
                               type outstream = _sig.TIO.StreamIO.outstream
                               type pos = Int64.int
                               type reader = TextPrimIO.reader
                               type vector = string
                               type writer = TextPrimIO.writer
                               val canInput: _sig.TIO.StreamIO.instream * int
                                             -> int option
                               val closeIn: _sig.TIO.StreamIO.instream -> unit
                               val closeOut: _sig.TIO.StreamIO.outstream -> unit
                               val endOfStream: _sig.TIO.StreamIO.instream -> bool
                               val filePosIn: _sig.TIO.StreamIO.instream
                                              -> Int64.int
                               val filePosOut: _sig.TIO.StreamIO.out_pos
                                               -> Int64.int
                               val flushOut: _sig.TIO.StreamIO.outstream -> unit
                               val getBufferMode: _sig.TIO.StreamIO.outstream
                                                  -> IO.buffer_mode
                               val getPosOut: _sig.TIO.StreamIO.outstream
                                              -> _sig.TIO.StreamIO.out_pos
                               val getReader: _sig.TIO.StreamIO.instream
                                              -> TextPrimIO.reader * string
                               val getWriter: _sig.TIO.StreamIO.outstream
                                              -> TextPrimIO.writer * IO.buffer_mode
                               val input: _sig.TIO.StreamIO.instream
                                          -> string * _sig.TIO.StreamIO.instream
                               val input1: _sig.TIO.StreamIO.instream
                                           -> (char * _sig.TIO.StreamIO.instream) option
                               val inputAll: _sig.TIO.StreamIO.instream
                                             -> string * _sig.TIO.StreamIO.instream
                               val inputLine: _sig.TIO.StreamIO.instream
                                              -> (string
                                                  * _sig.TIO.StreamIO.instream) option
                               val inputN: _sig.TIO.StreamIO.instream * int
                                           -> string * _sig.TIO.StreamIO.instream
                               val mkInstream: TextPrimIO.reader * string
                                               -> _sig.TIO.StreamIO.instream
                               val mkOutstream: TextPrimIO.writer * IO.buffer_mode
                                                -> _sig.TIO.StreamIO.outstream
                               val output: _sig.TIO.StreamIO.outstream * string
                                           -> unit
                               val output1: _sig.TIO.StreamIO.outstream * char
                                            -> unit
                               val outputSubstr: _sig.TIO.StreamIO.outstream
                                                 * char VectorSlice.slice
                                                 -> unit
                               val setBufferMode: _sig.TIO.StreamIO.outstream
                                                  * IO.buffer_mode
                                                  -> unit
                               val setPosOut: _sig.TIO.StreamIO.out_pos
                                              -> _sig.TIO.StreamIO.outstream
                            end
                      end
        spec at:   z.sml 46.23-46.25

Most of the 'signature: ..." diagnostics come from
`ElaborateEnv.Structure.layouts`, which aims to represent the
signature of the structure --- i.e., all types in the signature of the
structure are realized by the corresponding types of the structure.
This results in some unhelpful diagnostics, such as:

    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: T1.
        signature: structure T1: T
                                 where type U.u = _sig.T1.U.u
                                 where type t = _sig.T1.t
        spec at:   z.sml 14.17-14.18

which has the vacuous `where type U.u = _sig.T1.U.u` and
`where type t = _sig.T1.t` and:

    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: Z.Z2.
        signature: structure Z2:
                      sig
                         datatype z = C of unit
                      end
        spec at:   z.sml 27.23-27.24
which obscures the fact that `Z.Z2.u` is required to equal `Z.u`.
Commits ecfb3c7 and 5370b14 addressed similar issues for `Type in
structure by not in signature` diagnostics, but did not handle types
within signatures.

Now, MLton generates the following error messages:

    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: T1.
        signature: structure T1: T
        spec at:   z.sml 14.17-14.18
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: T2.
        signature: structure T2:
                      T where type U.u = _sig.T1.U.u
                        where type t = _sig.T1.t
        spec at:   z.sml 15.17-15.18
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: T3.
        signature: structure T3: T
        spec at:   z.sml 17.17-17.18
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: T4.
        signature: structure T4:
                      T where type U.u = _sig.T3.U.u
                        where type t = _sig.T3.t
        spec at:   z.sml 18.17-18.18
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: U.
        signature: structure U:
                      sig
                         datatype u = C of unit
                         val toString: _sig.U.u -> string
                      end
        spec at:   z.sml 5.17-5.17
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: Z.Z1.
        signature: structure Z.Z1:
                      sig
                         datatype z = C of unit
                      end
        spec at:   z.sml 23.23-23.24
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: Z.Z2.
        signature: structure Z.Z2:
                      sig
                         datatype z = datatype _sig.U.u
                      end
        spec at:   z.sml 27.23-27.24
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: Z.Z3.
        signature: structure Z.Z3:
                      sig
                         datatype z = datatype _sig.U.u
                      end
        spec at:   z.sml 31.23-31.24
    Error: z.sml 12.4-41.6.
      Structure in signature but not in structure: Z.Z4.
        signature: structure Z.Z4:
                      sig
                         datatype z = datatype _sig.U.u
                      end
        spec at:   z.sml 35.23-35.24
    Error: z.sml 12.4-41.6.
      Type in signature but not in structure: t.
        signature: type t
        spec at:   z.sml 3.12-3.12
    Error: z.sml 12.4-41.6.
      Variable in signature but not in structure: toString.
        signature: val toString: _sig.t -> string
        spec at:   z.sml 4.11-4.18
    Error: z.sml 47.17-47.31.
      Structure in argument signature but not in structure: TIO.
        signature: structure TIO: TEXT_IO
        spec at:   z.sml 46.23-46.25
    Error: z.sml 50.17-50.31.
      Structure in argument signature but not in structure: TIO.
        signature: structure TIO:
                      sig
                         structure StreamIO:
                            sig
                               type elem = char
                               type instream
                               type out_pos
                               type outstream
                               type pos = Int64.int
                               type reader = TextPrimIO.reader
                               type vector = string
                               type writer = TextPrimIO.writer
                               val canInput: _sig.TIO.StreamIO.instream * int
                                             -> int option
                               val closeIn: _sig.TIO.StreamIO.instream -> unit
                               val closeOut: _sig.TIO.StreamIO.outstream -> unit
                               ...
                               val setBufferMode: _sig.TIO.StreamIO.outstream
                                                  * IO.buffer_mode
                                                  -> unit
                               val setPosOut: _sig.TIO.StreamIO.out_pos
                                              -> _sig.TIO.StreamIO.outstream
                            end
                         type elem = char
                         type instream
                         type outstream
                         type vector = string
                         val canInput: _sig.TIO.instream * int -> int option
                         val closeIn: _sig.TIO.instream -> unit
                         val closeOut: _sig.TIO.outstream -> unit
                         ...
                         val stdIn: _sig.TIO.instream
                         val stdOut: _sig.TIO.outstream
                      end
        spec at:   z.sml 46.23-46.25

Rather than using `ElaborateEnv.Structure.layouts`, a new
`ElaborateEnv.transparentCut.layouts` function that aims to represent
an interface as realized by a flexible tycon map (to identify types
that should be abstract).  Also, since these appear in diagnostics,
very large signatures are elided.

It may be reasonable to refactor `ElaborateEnv.Structure.layouts` and
`ElaborateEnv.transparentCut.layouts` to a common implementation.