Do not use unif vars in elaboration of non-inferred types
Consider the following program:

    datatype t = T of nit

    val _ : 'a -> t = T
    val _ = T ()
    val _ = T 1
    val _ = T true

Previously, MLton generated the following error messages:

    Error: z.sml 1.19-1.21.
      Undefined type: nit.
    Error: z.sml 3.5-3.19.
      Pattern and expression disagree.
        pattern:    ['a] -> _
        expression: [???] -> _
        in: val 'a _: ('a -> t) = T
        note: type would escape its scope: 'a
        escape to: z.sml 1.1-1.21
    Error: z.sml 5.9-5.11.
      Constructor applied to incorrect argument.
        expects: [unit]
        but got: [int]
        in: T 1
    Error: z.sml 6.9-6.14.
      Constructor applied to incorrect argument.
        expects: [unit]
        but got: [bool]
        in: T true

Note that the bogus type constructor "nit" was replaced with a fresh
unification variable, leading to the incongruous error message about
the type variable 'a escaping to a datatype declaration.  Moreover,
the "T ()" expression unifies the unification variable with unit,
resulting in type errors for the "T 1" and "T true" expressions.

Now, MLton generates the following error messages:

    Error: z.sml 1.19-1.21.
      Undefined type: nit.
    Error: z.sml 3.5-3.19.
      Pattern and expression disagree.
        pattern:    ['a] -> _
        expression: [?.<nit>] -> _
        in: val 'a _: ('a -> t) = T
    Error: z.sml 4.9-4.12.
      Constructor applied to incorrect argument.
        expects: [?.<nit>]
        but got: [unit]
        in: T ()
    Error: z.sml 5.9-5.11.
      Constructor applied to incorrect argument.
        expects: [?.<nit>]
        but got: [int]
        in: T 1
    Error: z.sml 6.9-6.14.
      Constructor applied to incorrect argument.
        expects: [?.<nit>]
        but got: [bool]
        in: T true

Because the bogus type constructor "nit" occurs in a datatype
declaration, it is replaced with a fresh type constructor (unequal to
any other type).