Cosmetic improvements to type-error messages.
* Print optional resultType constraint in fun declaration clauses
* Print "in: " before fun declaration clause in error messages
* Print singleton Ast.Exp.FlatApp and Ast.Pat.FlatApp vectors without
  delimiting parens.

For example, with the following type-incorrect program

  fun f (x: int) : char = x : bool

MLton previously reported the error message:

  Error: z.sml 2.25.
    Expression and constraint disagree.
      expects: [bool]
      but got: [int]
      in: (x): bool
  Error: z.sml 2.18.
    Function result type disagrees with expression.
      result type: [char]
      expression:  [int]
      f ((x): int) = (x): bool

Now, MLton reports the error message:

  Error: z.sml 2.25.
    Expression and constraint disagree.
      expects: [bool]
      but got: [int]
      in: x: bool
  Error: z.sml 2.18.
    Function result type disagrees with expression.
      result type: [char]
      expression:  [int]
      in: f (x: int): char = x: bool

SVN r7568