Changed the admitsEquality field of built in tycons like int, word, char, etc. to be "Sometimes" instead of "Always".  This prevents an incorrect type error message in programs like the following.
structure S: sig type t = int end =
   struct
      datatype t = T
   end

Before this checkin, MLton would report:

Error: z.sml 1.14.
  Type t admits equality in signature but not in structure.
    not equality:

After the checkin, MLton reports:

Error: z.sml 1.14.
  Type definition in structure disagrees with signature.
    type: t
    structure: [t]
    signature: [int]