We need to prototype the basis FFI before use in Word-check.h. Therefore, include the header.
This fixes this regression:
testing fixed-integer
/tmp/file8kzjD6.12.c:137: error: conflicting types for 'WordS16_quot'
/Users/terpstra/src/mlton/mlton.x86_64/build/lib/include/basis/Word/Word-check.h:158: error: previous implicit declaration of 'WordS16_quot' was here
/tmp/file8kzjD6.12.c:139: error: conflicting types for 'WordS8_quot'
/Users/terpstra/src/mlton/mlton.x86_64/build/lib/include/basis/Word/Word-check.h:157: error: previous implicit declaration of 'WordS8_quot' was here
call to system failed with exit status 1:
gcc -std=gnu99 -c -I/Users/terpstra/src/mlton/mlton.x86_64/build/lib/include -O1 -fno-strict-aliasing -fomit-frame-pointer -w -I/sw/include -o /tmp/fileJro07X.o /tmp/file8kzjD6.12.c
compilation of fixed-integer failed with -type-check true



SVN r4578