Allow elaboration to proceed past function definition when errors
Previously, MLton stopped elaboration after elaborating a functor
definition if there were any reported errors, whether or not such
errors arose from the body of the functor.  For example, consider the
following two programs:

    (* z.sml *)
    val () = 1
    functor F () = struct end
    val () = 1

    (* y.sml *)
    functor F () = struct val () = 1 end
    val () = 1
    structure S = F ()

Previously, MLton reported the following errors:

    Error: z.sml 2.5-2.10.
      Pattern and expression disagree.
        pattern:    [unit]
        expression: [int]
        in: val () = 1

    Error: y.sml 2.27-2.32.
      Pattern and expression disagree.
        pattern:    [unit]
        expression: [int]
        in: val () = 1

Note that the second "val () = 1" declaration is not included among
the error messages.

Now, MLton reports the following errors:

    Error: z.sml 2.5-2.10.
      Pattern and expression disagree.
        pattern:    [unit]
        expression: [int]
        in: val () = 1
    Error: z.sml 4.5-4.10.
      Pattern and expression disagree.
        pattern:    [unit]
        expression: [int]
        in: val () = 1

    Error: y.sml 2.27-2.32.
      Pattern and expression disagree.
        pattern:    [unit]
        expression: [int]
        in: val () = 1
    Error: y.sml 3.5-3.10.
      Pattern and expression disagree.
        pattern:    [unit]
        expression: [int]
        in: val () = 1

Note that the error in the body of the functor is not repeated,
because the functor application is suppressed.