Improve error messages involving anonymous functor argument
Consider the following program:

    functor F1 (datatype t = T) =
    struct
       type t = unit
       val _ = [T, ()]
    end

Previously, MLton generated the following error message:

    Error: z.sml 4.16-4.17.
      List with element of different type.
        element:  [unit]
        previous: [ZZZNewStridZZZ.t]
        in: [T, ()]

Now, MLton generates the following error message:

      List with element of different type.
        element:  [unit]
        previous: [_arg.t]
        in: [T, ()]

Worse, consider the following (contrived) program:

    structure ZZZNewStridZZZ =
       struct
          datatype u = U
       end
    functor F1 (datatype t = T) =
    struct
       val u = ZZZNewStridZZZ.U
    end

Previously, MLton erroneously rejected this program:

    Error: z.sml 7.12-7.27.
      Undefined variable: ZZZNewStridZZZ.U.

because `ZZZNewStridZZZ` was used as the anonymous functor argument.

Now, MLton correctly accepts this program.