Fix uncaught Subscript exception in elaboration of function clauses.
An erroneous function declaration that has different numbers of
arguments in different clauses would raise an unhandled Subscript
exception:

[mtf@fenrir tmp]$ cat z.sml
fun f true false = #"a" | f _ = #"b"

val g = 1 + false

[mtf@fenrir tmp]$ ~/devel/mlton/mlton-20100608/build/bin/mlton z.sml
Error: z.sml 1.1.
  Function defined with different numbers of arguments.
    clause: f true false = #"a"
    clause: f _ = #"b"
unhandled exception: Subscript

This was due to the type checking of arguments that uses the first
clause as the canonical arguments and performs a Vector.sub on each
clause's patterns to select the corresponding argument.  For
subsequent clauses with fewer arguments than the first clause, this
raises the Subscript exception.

The solution is to inspect all clauses to determine the maximum number
of arguments, use fresh unification types as the canonical argument
types, and perform a bounds check to ignore clauses with fewer
arguments.

[mtf@fenrir tmp]$ ~/devel/mlton/mlton.svn.trunk/build/bin/mlton z.sml
Error: z.sml 1.1.
  Function defined with different numbers of arguments.
    clause: f true false = #"a"
    clause: f _ = #"b"
Error: z.sml 3.11.
  Function applied to incorrect argument.
    expects: _ * [int]
    but got: _ * [bool]
    in: + (1, false)
compilation aborted: parseAndElaborate reported errors



SVN r7497