In `setTyconNames`, process *all* decs in reverse time order
Previously, when looping through declarations to select the shortest
in-scope longtycon to use as the pretty name of a tycon, the top-level
types and structures were processed in reverse time order, but inner
types and structures were processed in alphabetical order.

Consider the following program:

    datatype a = A
    type z = a
    val _ = [(), A]

    structure S =
       struct
          datatype a = A
          type z = a
       end
    val _ = [(), S.A]

    datatype z = Z
    type a = z
    val _ = [(), Z]

    structure S =
       struct
          datatype z = Z
          type a = z
       end
    val _ = [(), S.Z]

    structure A = struct datatype a = A end
    structure B = struct type b = A.a end
    val _ = [(), A.A]

    structure S =
       struct
          structure A = struct datatype a = A end
          structure B = struct type b = A.a end
       end
    val _ = [(), S.A.A]

Previously, MLton generated the following error messages:

    Error: z.sml 3.14-3.14.
      List with element of different type.
        element:  [z]
        previous: [unit]
        in: [(), A]
    Error: z.sml 10.14-10.16.
      List with element of different type.
        element:  [S.a]
        previous: [unit]
        in: [(), S.A]
    Error: z.sml 14.14-14.14.
      List with element of different type.
        element:  [a]
        previous: [unit]
        in: [(), Z]
    Error: z.sml 21.14-21.16.
      List with element of different type.
        element:  [S.a]
        previous: [unit]
        in: [(), S.Z]
    Error: z.sml 25.14-25.16.
      List with element of different type.
        element:  [B.b]
        previous: [unit]
        in: [(), A.A]
    Error: z.sml 32.14-32.18.
      List with element of different type.
        element:  [S.A.a]
        previous: [unit]
        in: [(), S.A.A]

Note, for example, that while the first error message is in terms of
the top-level type 'z' (which is declared after 'a'), the second error
message is in terms of the type 'S.a', despite the fact that 'S.z' is
declared after 'S.a'.

Now, MLton generates the following error messages:

    Error: z.sml 3.14-3.14.
      List with element of different type.
        element:  [z]
        previous: [unit]
        in: [(), A]
    Error: z.sml 10.14-10.16.
      List with element of different type.
        element:  [S.z]
        previous: [unit]
        in: [(), S.A]
    Error: z.sml 14.14-14.14.
      List with element of different type.
        element:  [a]
        previous: [unit]
        in: [(), Z]
    Error: z.sml 21.14-21.16.
      List with element of different type.
        element:  [S.a]
        previous: [unit]
        in: [(), S.Z]
    Error: z.sml 25.14-25.16.
      List with element of different type.
        element:  [B.b]
        previous: [unit]
        in: [(), A.A]
    Error: z.sml 32.14-32.18.
      List with element of different type.
        element:  [S.B.b]
        previous: [unit]
        in: [(), S.A.A]