Proceed with generalized type in non-expansive dec after error
Consider the following program:

    val id: 'a -> 'a = fn x => x
    val f: 'a -> 'a = id id
    val g = id (fn (x: 'a) => x)

    val _ = (f 1, f true)

Previously, MLton generated the following diagnostics:

    Error: z.sml 2.5-2.5.
      Type of variable cannot be generalized in expansive declaration: f.
        type: ['a] -> ['a]
        in: val 'a f: ('a -> 'a) = id id
    Error: z.sml 3.5-3.5.
      Type of variable cannot be generalized in expansive declaration: g.
        type: ['a] -> ['a]
        in: val 'a g = id (fn x: 'a => x)
    Error: z.sml 5.15-5.20.
      Function applied to incorrect argument.
        expects: [int]
        but got: [bool]
        in: f true
    Warning: z.sml 3.5-3.5.
      Type of variable was not inferred and could not be generalized: g.
        type: ??? -> ???
        in: val 'a g = id (fn x: 'a => x)

Taking the type annotation on `f` as the user's intention, the
subsequent type error at the application `f true` is spurious.

Now, MLton generates the following diagnostics:

    Error: z.sml 2.5-2.5.
      Type of variable cannot be generalized in expansive declaration: f.
        type: ['a] -> ['a]
        in: val 'a f: ('a -> 'a) = id id
    Error: z.sml 3.5-3.5.
      Type of variable cannot be generalized in expansive declaration: g.
        type: ['a] -> ['a]
        in: val 'a g = id (fn x: 'a => x)