Mostly complete reintegration of generated basis library FFI.  Almost all regressions pass; something busted with sockets and with IntInf.
MLton MLTONVERSION (built Sun Jan 29 19:07:18 2006 on localhost.localdomain)
flags = -type-check true 
testing 10
testing 11
testing 12
testing 13
testing 14
testing 15
testing 16
testing 17
testing 18
testing 19
testing 1
testing 20
testing 21
testing 22
testing 23
testing 2
testing 3
testing 4
testing 5
testing 6
testing 7
testing 8
testing 9
testing abcde
testing abstype
testing all-overloads
testing array2
testing array3
testing array4
testing array5
testing array6
testing array7
testing array
testing asterisk
testing basis-sharing
testing big-array
testing binio
testing bool-triple
testing bytechar
testing callcc2
testing callcc3
testing callcc
testing cases
testing char0
testing char.scan
testing check_arrays
testing circular
testing cmdline
testing cobol
testing command-line
testing comment-end
testing constraint
testing conv2
0a1,6
> FailRead, base = BIN, str = |1000000000000000000000000000000|
> FailRead, base = BIN, str = |1000000000000000000000000000001|
> FailRead, base = BIN, str = |~1000000000000000000000000000001|
> FailRead, base = BIN, str = |1000000000000000000000000000010|
> FailRead, base = BIN, str = |~1000000000000000000000000000010|
> FailRead, base = BIN, str = |~10000000000000000000000000000000|
difference with -type-check true 
testing conv
1c1,44495308
< All ok
---
> Fail 3: ~1
difference with -type-check true 
testing cycle
testing datatype-with-free-tyvars
testing date
testing dead
testing deep-flatten
testing default-overloads
testing down
testing echo
1c1,3
< server processed 1900 bytes
---
> unhandled exception: SysErr: Invalid argument [inval]
> ./bin/regression: line 112: 30636 Terminated              ./$f
> Nonzero exit status.
difference with -type-check true 
testing eq
testing eqtype
testing exhaustive
testing exn2
testing exnHistory3
testing exnHistory
testing exn
testing expansive-valbind
testing exponential
testing ex
testing fact
testing fast2
testing fast
testing ffi-opaque
testing ffi
testing fft
testing filesys
testing finalize.2
testing finalize.3
testing finalize.4
testing finalize.5
testing finalize
testing fixed-integer
13a14,17
> Int31: abs ~1073741824 = Overflow <> ~1073741824
> Int31: ~ ~1073741824 = Overflow <> ~1073741824
> Int31: ~1073741824 div ~1 = Overflow <> ~1073741824
> Int31: ~1073741824 quot ~1 = Overflow <> ~1073741824
difference with -type-check true 
testing flat-array.2
testing flat-array.3
testing flat-array
testing flat-vector
testing flexrecord
testing format
testing ftruncate
testing FuhMishra
testing functor
testing gc-collect
testing general
testing grow-raise
testing harmonic
testing hello-world
testing id
testing int-inf.0
testing int-inf.1
testing int-inf.2
difference with -type-check true 
testing int-inf.3
1c1
< true12345
---
> true~9129
difference with -type-check true 
testing int-inf.4
testing int-inf.5
testing int-inf.bitops
testing int-inf.compare
difference with -type-check true 
testing int-inf.log2
6,12c6,7
< 30
< 31
< 32
< 32
< 33
< 33
< OK
---
> unhandled exception: Domain
> Nonzero exit status.
difference with -type-check true 
testing int-overflow
testing int
testing jump
testing kitdangle3
testing kitdangle
testing kitfib35
testing kitkbjul9
testing kitlife35u
testing kitloop2
testing kitmandelbrot
testing kitqsort
testing kitreynolds2
testing kitreynolds3
testing kitsimple
testing kittmergesort
testing kkb36c
testing kkb_eq
testing klife_eq
testing known-case0
testing known-case1
testing lambda-list-ref
testing layout
testing lex
testing lib
testing life
testing listpair
testing list
testing llv
testing local-ref
testing math
testing mlton.overload
testing mlton.share
testing mlton.word
testing modules
testing msort
testing mutex
testing nested-loop
testing nonexhaustive
testing once
testing only-one-exception
testing opaque2
testing opaque
testing open
testing os-exit
testing overloading
testing pack-real
testing pack
testing pack-word
testing parse
testing pat
testing poly-equal.2
testing poly-equal
testing polymorphic-recursion
testing posix-exit
testing posix-procenv
testing print-self
testing prodcons
testing pseudokit
testing real
testing ref-flatten.2
testing ref-flatten.3
testing ref-flatten.4
testing ref-flatten.5
testing ref-flatten.6
testing ref-flatten
testing ring
testing rlimit
Error: rlimit.sml 5.48.
  Undefined variable lockedInMemorySize.
Error: rlimit.sml 6.5.
  Undefined variable numProcesses.
Error: rlimit.sml 6.19.
  Undefined variable residentSetSize.
compilation aborted: parseAndElaborate reported errors
compilation of rlimit failed with -type-check true 
testing same-fringe
testing scon
testing semicolon
testing sharing
testing signals2
testing signals
testing sigs
testing size
testing slow2
testing slower
testing slow
testing smith-normal-form
testing socket
testing string2
testing stringcvt
testing string.fromString
testing string
testing substring-overflow
testing substring
testing suspend
testing tak
testing taut
testing testdyn1
testing testMatrix
testing textio.2
testing textio
testing thread0
testing thread1
testing thread2
testing thread-switch
testing time2
testing time3
testing time4
testing timeout
testing time
testing tststrcmp
testing type-check
testing typespec
testing unary.2
testing unary
testing undetermined
testing unixpath
testing useless-string
testing valrec
testing vector2
testing vector3
testing vector4
testing vector-loop
testing vector
testing weak
testing where-and
testing where
testing withtype
testing word8array
testing word8vector
testing word-all
testing wordn-array
testing word
testing world1
testing world2
testing world3
testing world4
testing world5
testing world6
testing barnes-hut
testing boyer
testing checksum
testing count-graphs
testing DLXSimulator
testing fft
testing fib
testing flat-array
skipping fxp
skipping hamlet
testing imp-for
testing knuth-bendix
testing lexgen
testing life
testing logic
testing mandelbrot
testing matrix-multiply
testing md5
testing merge
testing mlyacc
testing model-elimination
testing mpuz
testing nucleic
testing output1
testing peek
testing psdes-random
testing ratio-regions
testing ray
testing raytrace
testing simple
testing smith-normal-form
testing tailfib
testing tak
testing tensor
testing tsp
testing tyan
testing vector-concat
testing vector-rev
testing vliw
testing wc-input1
testing wc-scanStream
testing zebra
testing zern
testing mllex
testing mlyacc
testing mlprof



SVN r4330